### ISSUE TITLE
Parrots on the bar go away after a short time

### ISSUE THREAD

**Issue by INRIX-Kyle-Mistele** [mjaniszew/osx-touchbar-party-parrot#3]
After a short time after running `npm start`, the parrots disappear from the touch bar. Perhaps caused by clicking on a window?

**Comment by INRIX-Kyle-Mistele** [comment]
Never mind. You just have to have the electron window open.

**Comment by mjaniszew** [comment]
@INRIX-Kyle-Mistele correct, this is expected behaviour and that's how new MacBook's touchbar works by design, it has contextual area where controls for application you're currently focused on are displayed, which means that you have to be focused on electron window to have party parrots displayed.
